AWSTemplateFormatVersion : '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A sample SAM template for deploying Lambda functions.

Resources:
  lambdaThumbnail:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.amazonaws.lambda.thumbnail.Handler::handleRequest
      Runtime: java8
      CodeUri: target/thumbnail-1.0.0.jar
      MemorySize: 128
      Timeout: 30
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /thumbnail
            Method: post

